name: Python Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you want to use

    - name: Install dependencies
      run: pip install -r cloudsam/requirements.txt  # Adjust if needed

    - name: Run tests
      run: cd cloudsam/tests/unit && pytest test_dynamo.py  # Adjust if your test command is different
