name: Python Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you want to use

    - name: Install dependencies
      run: pip install -r cloudsam/requirements.txt  # Adjust if needed

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired region

    - name: Run tests
      run: cd cloudsam/tests/unit && pytest test_dynamo.py  # Adjust if your test command is different
